#!/bin/bash

function kill_port() {
    who=$1
    port=$2

    pid=$(netstat -tnlp 2>/dev/null | grep ":$port" | awk -F'LISTEN *|/' '/^(tcp|udp)/{print $2}')
    if [ -n "$pid" ]
    then
        kill $pid
        echo $who : Process $pid killed
    fi
    unset pid
}

function kill_all() {
    kill_port "Demo Webserver" "9000"
    kill_port "Keyword Extraction Server" "9001"
    kill_port "NER Server" "9002"
    kill_port "ETRI API" "9004"
    kill_port "Main Sentence Server" "9003"
}

trap "kill_all; exit" SIGHUP SIGINT SIGTERM

# check if someone is running the server
is_using=$(netstat -ntlp 2> /dev/null | grep :9000)
if [ -n "$is_using" ]; then
    echo "Someone is already running the server."
    while true; do
        read -p "Do you want to force quit it? (y/n)" yn
        case $yn in
            [Yy]* ) kill_all; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi
unset is_using
unset yn

source activate demo-webserver

# Execute Keyword Extraction Module
kill_port "Keyword Extraction Server" "9001"
python modules/keyword-extraction-server.py&

# Execute NER Module
kill_port "NER Server" "9002"
kill_port "ETRI API" "9004"
python modules/ner-server.py&
python modules/etri-api.py&

# Execute Main Sentence Extraction Module
kill_port "Main Sentence Extraction Server" "9003"
python modules/main-sentence-extraction-server.py&

# Execute Demo Webserver
kill_port "Demo Webserver" "9000"
node server.js